language: node_js
node_js: stable

cache:
    directories:
    - node_modules

install:
    - npm install

script:
    - hexo clean
    - hexo g

after_script:
    - cd ./public
    - git init
    - git config user.name "fox-ahri"
    - git config user.email "myfsnow@163.com"
    - git add .
    - git commit -m "Update docs"
    - git push --force --quiet "https://${ahrihexo}@${GH_REF}" master:gh-pages

branches:
    only:
        - master
env:
    global:
        - GH_REF: github.com/fox-ahri/ahrihexo.git
